// DAFTAR SISWA MASTER (VERSI 3.5)
// Total: 224 Data Siswa dengan Password Unik (1 Huruf + 4 Angka)

const SISWA_BARU = [
    { nama: "Aditya Ramadhani", kelas: "KELAS 10-1", pass: "A8231" },
    { nama: "Aira Nafisatul Ainiyah", kelas: "KELAS 10-1", pass: "B9012" },
    { nama: "Ajja Albar Jauj Apriss", kelas: "KELAS 10-1", pass: "C4421" },
    { nama: "Alderio Ilham Qodzafi", kelas: "KELAS 10-1", pass: "D1092" },
    { nama: "Aldy Kurniawan Saputra", kelas: "KELAS 10-1", pass: "E5531" },
    { nama: "Amelia Ng Jiaxin", kelas: "KELAS 10-1", pass: "F2093" },
    { nama: "Antonio Junior Liwa Putra", kelas: "KELAS 10-1", pass: "G8812" },
    { nama: "Aryan Dwi Nurbekti", kelas: "KELAS 10-1", pass: "H3341" },
    { nama: "Dafa Parvaiz Zechariah Windriyono", kelas: "KELAS 10-1", pass: "I7721" },
    { nama: "Dimas Maulana", kelas: "KELAS 10-1", pass: "J1102" },
    { nama: "Diva Alicia Putri", kelas: "KELAS 10-1", pass: "K6623" },
    { nama: "Era Fatravia", kelas: "KELAS 10-1", pass: "L4491" },
    { nama: "Fahza Aliya Putri", kelas: "KELAS 10-1", pass: "M3302" },
    { nama: "Faza Askia Tamma Al Faruq", kelas: "KELAS 10-1", pass: "N1192" },
    { nama: "Febri Ardiansyah Putra", kelas: "KELAS 10-1", pass: "O5582" },
    { nama: "Felcia Agasi", kelas: "KELAS 10-1", pass: "P4401" },
    { nama: "Fiza Arif Uqianus Fan", kelas: "KELAS 10-1", pass: "Q2291" },
    { nama: "Ghina Jifara Wangi", kelas: "KELAS 10-1", pass: "R3302" },
    { nama: "Jessi Tirta Dharma Ayu Puspayogi", kelas: "KELAS 10-1", pass: "S1192" },
    { nama: "Keysha Anindita Suri Pratama", kelas: "KELAS 10-1", pass: "T5582" },
    { nama: "Leavy Aqeyla Ayatul Husna", kelas: "KELAS 10-1", pass: "U4401" },
    { nama: "M Andy Begarrt Prassetyo", kelas: "KELAS 10-1", pass: "V2291" },
    { nama: "Marsya Dwi Saputri", kelas: "KELAS 10-1", pass: "W3302" },
    { nama: "Mutiara Safitri Mustofa", kelas: "KELAS 10-1", pass: "X1192" },
    { nama: "Nazlafatul Azizah", kelas: "KELAS 10-1", pass: "Y5582" },
    { nama: "Putri Rizqi Ria Sugiyarto", kelas: "KELAS 10-1", pass: "Z4401" },
    { nama: "Rera Mustika Resima", kelas: "KELAS 10-1", pass: "A2291" },
    { nama: "Riska Novita Putri", kelas: "KELAS 10-1", pass: "B3302" },
    { nama: "Safa Tiara Ramadani", kelas: "KELAS 10-1", pass: "C1192" },
    { nama: "Seyla Erfa Amanda Putri", kelas: "KELAS 10-1", pass: "D5582" },
    { nama: "Wifa Riski Ramadani", kelas: "KELAS 10-1", pass: "E4401" },

    // KELAS 10-2
    { nama: "Akhmad Fauzi Fadilah", kelas: "KELAS 10-2", pass: "F1039" },
    { nama: "Alvino Ganesha Putra", kelas: "KELAS 10-2", pass: "G2294" },
    { nama: "Ammar Sahadat Dirgantara", kelas: "KELAS 10-2", pass: "H3382" },
    { nama: "Anggita Fitri Fauziah", kelas: "KELAS 10-2", pass: "I4471" },
    { nama: "Aziziah Jacinda Ruela Mahsa Rahmadi", kelas: "KELAS 10-2", pass: "J5562" },
    { nama: "Baim", kelas: "KELAS 10-2", pass: "K6653" },
    { nama: "Dhaniel Arifin", kelas: "KELAS 10-2", pass: "L7744" },
    { nama: "Dina Aprilia", kelas: "KELAS 10-2", pass: "M8835" },
    { nama: "Eka Reza Ramadhani", kelas: "KELAS 10-2", pass: "N9926" },
    { nama: "Fahrizal Bahtiar Hamzah", kelas: "KELAS 10-2", pass: "O1017" },
    { nama: "Feliza Artha Jasmine", kelas: "KELAS 10-2", pass: "P2108" },
    { nama: "Galuh Saputri", kelas: "KELAS 10-2", pass: "Q3199" },
    { nama: "Gantari Zia Bhumyamca", kelas: "KELAS 10-2", pass: "R4280" },
    { nama: "Hana Fitria", kelas: "KELAS 10-2", pass: "S5371" },
    { nama: "Kevin Juliano Sandra Pratama", kelas: "KELAS 10-2", pass: "T6462" },
    { nama: "Marvin Nazalul Alfizar", kelas: "KELAS 10-2", pass: "U7553" },
    { nama: "Moh Ridho Dzikrullah", kelas: "KELAS 10-2", pass: "V8644" },
    { nama: "Mohammad Arya Raditya", kelas: "KELAS 10-2", pass: "W9735" },
    { nama: "Mohm Anas Maliki", kelas: "KELAS 10-2", pass: "X1826" },
    { nama: "Muhammad Ariansyah", kelas: "KELAS 10-2", pass: "Y2917" },
    { nama: "Mutiara Dwi Apriliani", kelas: "KELAS 10-2", pass: "Z3008" },
    { nama: "Myisha Amelia Jauhari", kelas: "KELAS 10-2", pass: "A4199" },
    { nama: "Nabila Gabrela Pradita", kelas: "KELAS 10-2", pass: "B5280" },
    { nama: "Naila Zulfi Az Zahra", kelas: "KELAS 10-2", pass: "C6371" },
    { nama: "Nayla Mufida", kelas: "KELAS 10-2", pass: "D7462" },
    { nama: "Nova Widiyanti", kelas: "KELAS 10-2", pass: "E8553" },
    { nama: "Revy Maulida Hasanah", kelas: "KELAS 10-2", pass: "F9644" },
    { nama: "Rista Ayu Putri", kelas: "KELAS 10-2", pass: "G1735" },
    { nama: "Sofiatul Azizah", kelas: "KELAS 10-2", pass: "H2826" },
    { nama: "Widya Julita Saputri", kelas: "KELAS 10-2", pass: "I3917" },
    { nama: "Zahra Thusita", kelas: "KELAS 10-2", pass: "J4008" },
    { nama: "Zelvia Ayu Verasari", kelas: "KELAS 10-2", pass: "K5199" },

    // KELAS 10-3
    { nama: "Alysa Rani Zalianti", kelas: "KELAS 10-3", pass: "L6210" },
    { nama: "Asyafa Zahra Salsabilla", kelas: "KELAS 10-3", pass: "M7301" },
    { nama: "Aulia Zulfalita Pratama", kelas: "KELAS 10-3", pass: "N8492" },
    { nama: "Catur Ahmad Hasyim", kelas: "KELAS 10-3", pass: "O9583" },
    { nama: "Cheisya Anjela Putri", kelas: "KELAS 10-3", pass: "P1674" },
    { nama: "Devi Wulan Savira", kelas: "KELAS 10-3", pass: "Q2765" },
    { nama: "Dhea Bunga Aprillia", kelas: "KELAS 10-3", pass: "R3856" },
    { nama: "Dinda Sekar Arumni", kelas: "KELAS 10-3", pass: "S4947" },
    { nama: "Dinda Septiana Dewi", kelas: "KELAS 10-3", pass: "T5038" },
    { nama: "Ega Fabian Yafa", kelas: "KELAS 10-3", pass: "U6129" },
    { nama: "Fahrina Bunga Aprillia", kelas: "KELAS 10-3", pass: "V7210" },
    { nama: "Firdaus Ibnu Hadi", kelas: "KELAS 10-3", pass: "W8301" },
    { nama: "Franda Aprilia Wuri Hartono", kelas: "KELAS 10-3", pass: "X9492" },
    { nama: "Geysa Hasta Saputra", kelas: "KELAS 10-3", pass: "Y1583" },
    { nama: "Gilang Fitrah Darmawan", kelas: "KELAS 10-3", pass: "Z2674" },
    { nama: "Icha Izzatul Jannah", kelas: "KELAS 10-3", pass: "A3765" },
    { nama: "Moh Azizul Hilmi", kelas: "KELAS 10-3", pass: "B4856" },
    { nama: "Mohammad Vale Septino Rossi", kelas: "KELAS 10-3", pass: "C5947" },
    { nama: "Muh. Irfan", kelas: "KELAS 10-3", pass: "D6038" },
    { nama: "Nabila Putri Awalia", kelas: "KELAS 10-3", pass: "E7129" },
    { nama: "Naysila Dwi Sasa Bila Putri Suryanto", kelas: "KELAS 10-3", pass: "F8210" },
    { nama: "Putri Aura Margareta", kelas: "KELAS 10-3", pass: "G9301" },
    { nama: "Rahel Niluh Agustina", kelas: "KELAS 10-3", pass: "H1492" },
    { nama: "Ramadhan Tegar Pamuji", kelas: "KELAS 10-3", pass: "I2583" },
    { nama: "Risma Ainun Nafiah", kelas: "KELAS 10-3", pass: "J3674" },
    { nama: "Robby Jati Murti", kelas: "KELAS 10-3", pass: "K4765" },
    { nama: "Suci Lintang Kinasih", kelas: "KELAS 10-3", pass: "L5856" },
    { nama: "Valecia Anggraeni Sasmita Putri", kelas: "KELAS 10-3", pass: "M6947" },
    { nama: "Wahyu Rizky Ramdhani", kelas: "KELAS 10-3", pass: "N7038" },
    { nama: "Wanda Putri Aprilia", kelas: "KELAS 10-3", pass: "O8129" },
    { nama: "Yoriza Danish Silvierra", kelas: "KELAS 10-3", pass: "P9210" },

    // KELAS 10-4
    { nama: "Amelia Junita Cahyani", kelas: "KELAS 10-4", pass: "Q1122" },
    { nama: "Andrianu Dwi Putra Kusuma", kelas: "KELAS 10-4", pass: "R2233" },
    { nama: "Bayu Putra Ramadhan", kelas: "KELAS 10-4", pass: "S3344" },
    { nama: "Cahyarani Faturohmah", kelas: "KELAS 10-4", pass: "T4455" },
    { nama: "Citra Ayu Vergita", kelas: "KELAS 10-4", pass: "U5566" },
    { nama: "Disty Eka Febiana", kelas: "KELAS 10-4", pass: "V6677" },
    { nama: "Diva Puspita Sari", kelas: "KELAS 10-4", pass: "W7788" },
    { nama: "Ferdy Id Andry Yanto", kelas: "KELAS 10-4", pass: "X8899" },
    { nama: "Fitri Nur Aini", kelas: "KELAS 10-4", pass: "Y9911" },
    { nama: "Iga Mahareza", kelas: "KELAS 10-4", pass: "Z1022" },
    { nama: "Ketut Sony Loke Budi Wiguna", kelas: "KELAS 10-4", pass: "A2133" },
    { nama: "Mayla Aura Andini", kelas: "KELAS 10-4", pass: "B3244" },
    { nama: "Meyka Nindi Agustin", kelas: "KELAS 10-4", pass: "C4355" },
    { nama: "Moh. Rafka Eka Mannansyah", kelas: "KELAS 10-4", pass: "D5466" },
    { nama: "Mohammad Ibra Ravito", kelas: "KELAS 10-4", pass: "E6577" },
    { nama: "Mohraffi Alfaridzi Ardiansyah", kelas: "KELAS 10-4", pass: "F7688" },
    { nama: "Muhamad Artha Mauridho", kelas: "KELAS 10-4", pass: "G8799" },
    { nama: "Muhammad Wahyu Puji Nugraha", kelas: "KELAS 10-4", pass: "H9811" },
    { nama: "Naura Gellicia Tiffany", kelas: "KELAS 10-4", pass: "I1922" },
    { nama: "Okta Dwi Nuraini", kelas: "KELAS 10-4", pass: "J2033" },
    { nama: "Rahma Taufik Ridani", kelas: "KELAS 10-4", pass: "K3144" },
    { nama: "Raka Putra Anggara", kelas: "KELAS 10-4", pass: "L4255" },
    { nama: "Sandy Virzatullah", kelas: "KELAS 10-4", pass: "M5366" },
    { nama: "Selvia Junita", kelas: "KELAS 10-4", pass: "N6477" },
    { nama: "Shinta Metta Lestari Ningsih", kelas: "KELAS 10-4", pass: "O7588" },
    { nama: "Stefa Rina Putri Anindita", kelas: "KELAS 10-4", pass: "P8699" },
    { nama: "Suluh Prabandaru", kelas: "KELAS 10-4", pass: "Q9711" },
    { nama: "Vanesa Septiana Putri", kelas: "KELAS 10-4", pass: "R1822" },
    { nama: "Wawendra Wahyu Bimarta", kelas: "KELAS 10-4", pass: "S2933" },
    { nama: "Wulan Ceisha Ramadani", kelas: "KELAS 10-4", pass: "T3044" },
    { nama: "Yeni Dwi Prastyani", kelas: "KELAS 10-4", pass: "U4155" },
    { nama: "Yuyun Alfiana", kelas: "KELAS 10-4", pass: "V5266" },

    // KELAS 10-5
    { nama: "Aisyah Okta Livina Laurenz", kelas: "KELAS 10-5", pass: "W6310" },
    { nama: "Alfida Hildana Aprilia", kelas: "KELAS 10-5", pass: "X7421" },
    { nama: "Amiral Jordan Arva", kelas: "KELAS 10-5", pass: "Y8532" },
    { nama: "Anggun Virma Virnanda Devi", kelas: "KELAS 10-5", pass: "Z9643" },
    { nama: "Aura Cintya Arbiela Putri", kelas: "KELAS 10-5", pass: "A1754" },
    { nama: "Aura Kirana Maulida", kelas: "KELAS 10-5", pass: "B2865" },
    { nama: "Cesya Mawra Pawlina Sari", kelas: "KELAS 10-5", pass: "C3976" },
    { nama: "Dea Nofa Leona Dewi", kelas: "KELAS 10-5", pass: "D4087" },
    { nama: "Eko Harianto", kelas: "KELAS 10-5", pass: "E5198" },
    { nama: "Farelio Brilyan Syah", kelas: "KELAS 10-5", pass: "F6210" },
    { nama: "Frisya Maulida Santika", kelas: "KELAS 10-5", pass: "G7321" },
    { nama: "Geisha Dwi Aprilia", kelas: "KELAS 10-5", pass: "H8432" },
    { nama: "Gytha Athiva Qanita Azaria", kelas: "KELAS 10-5", pass: "I9543" },
    { nama: "Lenny Zhifilia Nugrahani", kelas: "KELAS 10-5", pass: "J1654" },
    { nama: "Maulana Ishak", kelas: "KELAS 10-5", pass: "K2765" },
    { nama: "Moh Fakhri Lutfi", kelas: "KELAS 10-5", pass: "L3876" },
    { nama: "Mohammad Soeltan Sofyan Arridho", kelas: "KELAS 10-5", pass: "M4987" },
    { nama: "Muhamad Fahrezi", kelas: "KELAS 10-5", pass: "N5098" },
    { nama: "Muhamad Nata Maurino", kelas: "KELAS 10-5", pass: "O6110" },
    { nama: "Muhammad Khoiron Thoifur A.", kelas: "KELAS 10-5", pass: "P7221" },
    { nama: "Nadifah Farhanatul Mabruroh", kelas: "KELAS 10-5", pass: "Q8332" },
    { nama: "Nadin Sya Prawesti", kelas: "KELAS 10-5", pass: "R9443" },
    { nama: "Neng Ayu Javanza Quine Yuandri", kelas: "KELAS 10-5", pass: "S1554" },
    { nama: "Nurul Izzati", kelas: "KELAS 10-5", pass: "T2665" },
    { nama: "Putri Bunga Cahyani", kelas: "KELAS 10-5", pass: "U3776" },
    { nama: "Rafansyah Wahyu Pratama", kelas: "KELAS 10-5", pass: "V4887" },
    { nama: "Rega Tegar Maulana Hakiki", kelas: "KELAS 10-5", pass: "W5998" },
    { nama: "Senja Dinanti", kelas: "KELAS 10-5", pass: "X6010" },
    { nama: "Syerila Silfi Maulida Syafii", kelas: "KELAS 10-5", pass: "Y7121" },
    { nama: "Tiara Ayu Sabrina", kelas: "KELAS 10-5", pass: "Z8232" },
    { nama: "Wulidatul Afifah", kelas: "KELAS 10-5", pass: "A9343" },

    // KELAS 10-6
    { nama: "Ajeng Ulandari", kelas: "KELAS 10-6", pass: "B1144" },
    { nama: "Annisa Putri Zhaki", kelas: "KELAS 10-6", pass: "C2255" },
    { nama: "Aurel Jihan Panesa", kelas: "KELAS 10-6", pass: "D3366" },
    { nama: "Aviza Kirana Putri", kelas: "KELAS 10-6", pass: "E4477" },
    { nama: "Bunga Rachmatyas Mahani", kelas: "KELAS 10-6", pass: "F5588" },
    { nama: "Chen Lixin Nur Zaskia", kelas: "KELAS 10-6", pass: "G6699" },
    { nama: "Dela Cahya Maulita", kelas: "KELAS 10-6", pass: "H7711" },
    { nama: "Devi Mareta", kelas: "KELAS 10-6", pass: "I8822" },
    { nama: "Elina Amelia Margareta", kelas: "KELAS 10-6", pass: "J9933" },
    { nama: "Holidatul Fitri", kelas: "KELAS 10-6", pass: "K1044" },
    { nama: "I Gede Putra Yasa", kelas: "KELAS 10-6", pass: "L2155" },
    { nama: "Kiki Rosa Kamila", kelas: "KELAS 10-6", pass: "M3266" },
    { nama: "Linda Tri Yuliyani", kelas: "KELAS 10-6", pass: "N4377" },
    { nama: "Lutfi Aril Prayoga", kelas: "KELAS 10-6", pass: "O5488" },
    { nama: "Meylanie Anggi Zaziva", kelas: "KELAS 10-6", pass: "P6599" },
    { nama: "Moh Danial Herdyansah", kelas: "KELAS 10-6", pass: "Q7611" },
    { nama: "Mohammad Toriq Hidayah", kelas: "KELAS 10-6", pass: "R8722" },
    { nama: "Muhafreza Saputra", kelas: "KELAS 10-6", pass: "S9833" },
    { nama: "Muhammad Ibrahimmovic", kelas: "KELAS 10-6", pass: "T1944" },
    { nama: "Nanda Sasmita", kelas: "KELAS 10-6", pass: "U2055" },
    { nama: "Poni Agriandari", kelas: "KELAS 10-6", pass: "V3166" },
    { nama: "Rahma Intan Permadhani", kelas: "KELAS 10-6", pass: "W4277" },
    { nama: "Refan Abi Firmansyah", kelas: "KELAS 10-6", pass: "X5388" },
    { nama: "Riska Maulidi Ulfa", kelas: "KELAS 10-6", pass: "Y6499" },
    { nama: "Saskia Putri Cahyaningtyas", kelas: "KELAS 10-6", pass: "Z7511" },
    { nama: "Septian Surya Rhomadhoni", kelas: "KELAS 10-6", pass: "A8622" },
    { nama: "Sofyan Zahuri Abdullah", kelas: "KELAS 10-6", pass: "B9733" },
    { nama: "Syava Dyani Putri", kelas: "KELAS 10-6", pass: "C1844" },
    { nama: "Vana Aghista Ramadhani", kelas: "KELAS 10-6", pass: "D2955" },
    { nama: "Zelih Aurela", kelas: "KELAS 10-6", pass: "E3066" },
    { nama: "Dita Kharisma Dwi", kelas: "KELAS 10-6", pass: "F4177" },

    // KELAS 10-7
    { nama: "Achmad Fairus Raditya", kelas: "KELAS 10-7", pass: "G5288" },
    { nama: "Ah Farel Yanuar D.S.", kelas: "KELAS 10-7", pass: "H6399" },
    { nama: "Alvian Marifatul Abror", kelas: "KELAS 10-7", pass: "I7411" },
    { nama: "Andika Prasetya", kelas: "KELAS 10-7", pass: "J8522" },
    { nama: "Anggun Tri Mulyani", kelas: "KELAS 10-7", pass: "K9633" },
    { nama: "Caca Herliana Putri", kelas: "KELAS 10-7", pass: "L1744" },
    { nama: "Dila Agustiya Nengseh", kelas: "KELAS 10-7", pass: "M2855" },
    { nama: "Fathir Lanang Y.", kelas: "KELAS 10-7", pass: "N3966" },
    { nama: "Feby Putri Sugiansyah", kelas: "KELAS 10-7", pass: "O4077" },
    { nama: "Flora Ayu Valencya", kelas: "KELAS 10-7", pass: "P5188" },
    { nama: "Fredyco Raka", kelas: "KELAS 10-7", pass: "Q6299" },
    { nama: "Jayanti Bunga Lestari", kelas: "KELAS 10-7", pass: "R7311" },
    { nama: "Kayla Maretha Putri Puspitarini", kelas: "KELAS 10-7", pass: "S8422" },
    { nama: "Lavenia Vega Putri Manik", kelas: "KELAS 10-7", pass: "T9533" },
    { nama: "Moh Arlyn Dwi Andika", kelas: "KELAS 10-7", pass: "U1644" },
    { nama: "Moh. Rifki Nurhidayat", kelas: "KELAS 10-7", pass: "V2755" },
    { nama: "Mohamad Alfian Maulana", kelas: "KELAS 10-7", pass: "W3866" },
    { nama: "Mohamad Andrian Maulana", kelas: "KELAS 10-7", pass: "X4977" },
    { nama: "Muhamad Azam Mubarok", kelas: "KELAS 10-7", pass: "Y5088" },
    { nama: "Muhamad Danar Izha Rohil", kelas: "KELAS 10-7", pass: "Z6199" },
    { nama: "Muhammad Priya Daniel W.", kelas: "KELAS 10-7", pass: "A7211" },
    { nama: "Muzdhalifa", kelas: "KELAS 10-7", pass: "B8322" },
    { nama: "Nagita Nur Oktaviani", kelas: "KELAS 10-7", pass: "C9433" },
    { nama: "Naila Izza Nurjanah", kelas: "KELAS 10-7", pass: "D1544" },
    { nama: "Nora Sahbania Fachrozie", kelas: "KELAS 10-7", pass: "E2655" },
    { nama: "Ramadhan", kelas: "KELAS 10-7", pass: "F3766" },
    { nama: "Reyno Arventa Hadin Pratama", kelas: "KELAS 10-7", pass: "G4877" },
    { nama: "Salma Rahadatul Aisy", kelas: "KELAS 10-7", pass: "H5988" },
    { nama: "Septina Auliya Ramadani", kelas: "KELAS 10-7", pass: "I6011" },
    { nama: "Siti Putri Nur Aiyizah", kelas: "KELAS 10-7", pass: "J7122" },
    { nama: "Stefani Angelina Darmanota", kelas: "KELAS 10-7", pass: "K8233" },
    { nama: "Vierra Dipuspa Deshinta Sugiono", kelas: "KELAS 10-7", pass: "L9344" }
];
